### ISSUE TITLE
omg

### ISSUE THREAD

**Issue by laeakkk** [rafi1212122/BH3_PS#1]
at connectionFailureError (J:\BH3_PS-master\BH3_PS-master\node_modules\mongodb\lib\cmap\connect.js:387:20)
[1]             at Socket.<anonymous> (J:\BH3_PS-master\BH3_PS-master\node_modules\mongodb\lib\cmap\connect.js:310:22)
[1]             at Object.onceWrapper (node:events:628:26)
[1]             at Socket.emit (node:events:513:28)
[1]             at emitErrorNT (node:internal/streams/destroy:151:8)
[1]             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[1]           cause: Error: connect ECONNREFUSED ::1:27017
[1]               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
[1]             errno: -4078,
[1]             code: 'ECONNREFUSED',
[1]             syscall: 'connect',

**Comment by wcjqwq** [comment]
Error has indicated that mongo cannot connect

**Comment by laeakkk** [comment]
[12:43:30] <HTTP> HTTP server listening on port 80 & 443
[1] J:\1\BH3Smaster\node_modules\mongodb\lib\sdam\topology.js:285
[1]                 const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
[1]                                      ^
[1]
[1] MongoServerSelectionError: connect ECONNREFUSED ::1:27017
[1]     at Timeout._onTimeout (J:\1\BH3Smaster\node_modules\mongodb\lib\sdam\topology.js:285:38)
[1]     at listOnTimeout (node:internal/timers:564:17)
[1]     at process.processTimers (node:internal/timers:507:7) {
[1]   reason: TopologyDescription {
[1]     type: 'Unknown',
[1]     servers: Map(1) {
[1]       'localhost:27017' => ServerDescription {
[1]         address: 'localhost:27017',
[1]         type: 'Unknown',
[1]         hosts: [],
[1]         passives: [],
[1]         arbiters: [],
[1]         tags: {},
[1]         minWireVersion: 0,
[1]         maxWireVersion: 0,
[1]         roundTripTime: -1,
[1]         lastUpdateTime: 1362629,
[1]         lastWriteDate: 0,
[1]         error: MongoNetworkError: connect ECONNREFUSED ::1:27017
[1]             at connectionFailureError (J:\1\BH3Smaster\node_modules\mongodb\lib\cmap\connect.js:387:20)
[1]             at Socket.<anonymous> (J:\1\BH3Smaster\node_modules\mongodb\lib\cmap\connect.js:310:22)
[1]             at Object.onceWrapper (node:events:628:26)
[1]             at Socket.emit (node:events:513:28)
[1]             at emitErrorNT (node:internal/streams/destroy:151:8)
[1]             at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[1]             at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[1]           cause: Error: connect ECONNREFUSED ::1:27017
[1]               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
[1]             errno: -4078,
[1]             code: 'ECONNREFUSED',
[1]             syscall: 'connect',
[1]             address: '::1',
[1]             port: 27017
[1]           },
[1]           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
[1]         },
[1]         topologyVersion: null,
[1]         setName: null,
[1]         setVersion: null,
[1]         electionId: null,
[1]         logicalSessionTimeoutMinutes: null,
[1]         primary: null,
[1]         me: null,
[1]         '$clusterTime': null
[1]       }
[1]     },
[1]     stale: false,
[1]     compatible: true,
[1]     heartbeatFrequencyMS: 10000,
[1]     localThresholdMS: 15,
[1]     setName: null,
[1]     maxElectionId: null,
[1]     maxSetVersion: null,
[1]     commonWireVersion: 0,
[1]     logicalSessionTimeoutMinutes: null
[1]   },
[1]   code: undefined,
[1]   [Symbol(errorLabels)]: Set(0) {}
[1] }
[1]
[1] Node.js v18.9.0
