### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:80

### ISSUE THREAD

**Issue by dfmjndm** [rafi1212122/BH3_PS#21]
PS F:\BH3_PS> npm start

> bh_ps@1.0.0 start
> node --max_old_space_size=8192 -r ts-node/register index.ts --respawn --transpile-only

[16:52:58] <GLOBAL> Staring server...
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1723:21)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (F:\BH3_PS\node_modules\express\lib\application.js:635:24)
    at HttpServer.start (F:\BH3_PS\server\http\HttpServer.ts:49:18)
    at Object.<anonymous> (F:\BH3_PS\index.ts:13:26)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module.m._compile (F:\BH3_PS\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .ts] (F:\BH3_PS\node_modules\ts-node\src\index.ts:1621:12) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}

I have tried to run the command in administrator mode ,it still shows

**Comment by rafi1212122** [comment]
it's highly likely that other program is using port 80 (examples: xampp, ..others http server)
